// The AMA knowledge base. Add freely. After editing, run `npm run embed-qa`
// to regenerate qa-embeddings.json. Each entry's `q` and `aliases` are used
// to compute embeddings; the `a` is what's shown to the visitor.
export const qa = [
  {
    id: "education",
    q: "where did you go to school",
    aliases: ["what university", "education", "degree", "study", "college", "gpa"],
    a: "CS at McMaster — co-op stream, graduating in 2027.",
  },
  {
    id: "current-job",
    q: "where do you work",
    aliases: ["current job", "where do you intern", "are you interning", "current role", "what's your job"],
    a: "Cloud Database Engineer Intern at Huawei — been there a year now (since May 2025) and continuing through summer 2026. Resume has the gritty details.",
  },
  {
    id: "huawei",
    q: "tell me about your time at huawei",
    aliases: ["huawei", "huawei internship", "what do you do at huawei", "your huawei role"],
    a: "Cloud-native databases — MySQL and PostgreSQL day to day. I've been there a year now and I'm continuing through this summer. Resume has the specifics.",
  },
  {
    id: "mcmaster-research",
    q: "tell me about your research at mcmaster",
    aliases: ["mcmaster research", "research role", "undergrad research", "research assistant"],
    a: "I did research at McMaster the summer before Huawei — ISA-level systems work in Haskell. Brain-bending in a good way. Resume covers it.",
  },
  {
    id: "stack",
    q: "what's your stack",
    aliases: ["what languages do you use", "tech stack", "what tools", "what do you code in", "what skills"],
    a: "Python, C/C++, and TypeScript are the ones I reach for. MySQL and PostgreSQL daily at the internship. Next.js + Tailwind on the frontend, GCP and Docker on the ops side.",
  },
  {
    id: "favorite-project",
    q: "what's your favorite project",
    aliases: ["best project", "proudest of", "favorite thing you built"],
    a: "Right now, this portfolio — the AMA is retrieval-based, not an LLM, on purpose. Honorable mention: the RISC-V interpreter from research, which was the first time code felt like math to me.",
  },
  {
    id: "this-site",
    q: "how does this site work",
    aliases: ["how does the ama work", "how is this built", "is this chatgpt", "is this an llm", "behind the ama"],
    a: "Not an LLM at runtime. I wrote a Q&A bank, embedded each entry once at build time, and the live request just embeds your question and returns the closest match. Cheaper, stricter, can't hallucinate.",
  },
  {
    id: "hobbies",
    q: "what do you do for fun",
    aliases: ["hobbies", "interests outside code", "what do you do when not coding", "free time"],
    a: "Rock climbing, badminton, gym.",
  },
  {
    id: "climbing",
    q: "tell me about climbing",
    aliases: ["rock climbing", "bouldering", "do you climb"],
    a: "I boulder. It's the same loop as engineering — observe, hypothesize, try, fail, retune.",
  },
  {
    id: "badminton",
    q: "do you play badminton",
    aliases: ["badminton", "racket sports"],
    a: "Casually — friends, rallies, no ladder.",
  },
  {
    id: "location",
    q: "where are you based",
    aliases: ["where do you live", "location", "city"],
    a: "Hamilton during the school year. This summer I'm commuting to Markham every day for the internship.",
  },
  {
    id: "contact",
    q: "how can I reach you",
    aliases: ["contact", "email me", "your email", "get in touch", "reach you"],
    a: "Email is the best path: allisonzhao.uni@gmail.com. LinkedIn works too.",
  },
  {
    id: "open-to-work",
    q: "are you open to work",
    aliases: ["are you hiring", "looking for a job", "internship", "available for work", "next role"],
    a: "Open to new-grad SWE roles and future internships. Cloud, infra, databases, agents — anywhere I get to keep learning. allisonzhao.uni@gmail.com is the inbox.",
  },
  {
    id: "favorite-language",
    q: "what's your favorite programming language",
    aliases: ["favorite language", "preferred language"],
    a: "Python, C/C++, and TypeScript. Python for ideas, C/C++ when I want to feel something, TypeScript when I want the compiler to keep me honest.",
  },
  {
    id: "now-reading",
    q: "what are you reading right now",
    aliases: ["currently reading", "book right now", "what's on your desk", "favorite book", "reading list"],
    a: "Cracking the Coding Interview — perfect for the commute.",
  },
  {
    id: "claude",
    q: "do you use ai for coding",
    aliases: ["claude code", "do you use claude", "do you use copilot", "ai tools", "coding assistants"],
    a: "Yes — agentic coding tools daily. The interesting question isn't 'does AI write code,' it's 'where is your judgment still load-bearing.'",
  },
  {
    id: "music",
    q: "what music do you listen to",
    aliases: ["favorite music", "favorite artist", "what's on your spotify", "music taste"],
    a: "C-pop, some K-pop, and instrumental.",
  },
  {
    id: "ide",
    q: "what editor do you use",
    aliases: ["vscode", "vim", "editor", "ide"],
    a: "VSCode, with Claude Code wired in.",
  },
  {
    id: "now-doing",
    q: "what are you working on right now",
    aliases: ["current project", "what's next", "what are you building"],
    a: "Day job is the Huawei internship. Off-hours I'm cycling through agent projects — see the Projects panel for what's currently in flight.",
  },
  {
    id: "agents",
    q: "what are you building with agents",
    aliases: ["agent projects", "ai projects", "llm projects", "what agents", "what are you doing with ai"],
    a: "A handful of small things — testforge (multi-agent test quality), arxiv-rag (Q&A over papers), composio experiments. The Projects panel has the current list.",
  },
  {
    id: "ai-trends",
    q: "what are you learning in ai",
    aliases: ["ai exploration", "ai trends", "what's interesting in ai", "what are you exploring"],
    a: "I'm sampling broadly right now — agents, retrieval, evals, tooling. Rather understand one thing deeply than collect ten shallow demos.",
  },
  {
    id: "day-structure",
    q: "what does your day look like",
    aliases: ["typical day", "daily schedule", "routine"],
    a: "Long commute to Markham in the morning, deep work block midday, commute home, build something at night. The Day panel reflects this.",
  },
  {
    id: "commute",
    q: "your commute is long",
    aliases: ["long commute", "two hour commute", "how do you commute"],
    a: "Yeah — Markham is a haul. I read or do LeetCode on the train; turns out long commutes are decent for grinding fundamentals.",
  },
  {
    id: "leetcode",
    q: "do you do leetcode",
    aliases: ["competitive programming", "leetcode practice", "interview prep"],
    a: "Most days. 52 solved so far — the panel on the page is real, manually updated.",
  },
  {
    id: "why-databases",
    q: "why databases",
    aliases: ["why are you into databases", "what's interesting about databases", "why cloud"],
    a: "Cloud databases are where state, distributed systems, and operational stakes all collide. Patience pays off there.",
  },
  {
    id: "open-source",
    q: "do you contribute to open source",
    aliases: ["open source", "oss contributions", "github contributions"],
    a: "Smaller PRs here and there. Want to do a sustained block on one project this year.",
  },
  {
    id: "writing",
    q: "do you write",
    aliases: ["blog", "do you have a blog", "writing", "essays"],
    a: "Not yet — but the /posts route is reserved and v2 of this site will switch it on.",
  },
  {
    id: "design",
    q: "did you design this site",
    aliases: ["who designed this", "is this a template", "where's the template from"],
    a: "Designed it myself. The 'operator console' direction was deliberate — most portfolios feel like the same dashboard template. This one wants to feel like a system you log into.",
  },
  {
    id: "deltahacks",
    q: "tell me about deltahacks",
    aliases: ["hackathon", "deltahacks", "your hackathon", "extracurriculars"],
    a: "I'm VP Logistics for DeltaHacks, McMaster's hackathon. Also mentor with McMaster Start Coding.",
  },
  {
    id: "advice",
    q: "advice for cs students",
    aliases: ["advice for students", "tips for cs students", "what should I learn"],
    a: "Build one thing all the way to done, even if it's small. The completion taste is rarer than the building skill.",
  },
  {
    id: "values",
    q: "what do you care about in software",
    aliases: ["values", "what makes good software", "engineering principles", "philosophy"],
    a: "Software is how I get ideas out of my head. I have a lot of ideas, so I'm always pushing myself toward 'build fast, ship fast.' Boring code, fast feedback, courage to delete — those help.",
  },
];
